# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/ui_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 534)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 481, 441))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(10, 460, 90, 32))
        self.resetButton.setObjectName("resetButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(520, 270, 251, 200))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.runningTimeLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.runningTimeLabel.setObjectName("runningTimeLabel")
        self.verticalLayout.addWidget(self.runningTimeLabel)
        self.runningTimeLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.runningTimeLineEdit.setEnabled(True)
        self.runningTimeLineEdit.setObjectName("runningTimeLineEdit")
        self.verticalLayout.addWidget(self.runningTimeLineEdit)
        self.costLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.costLabel.setObjectName("costLabel")
        self.verticalLayout.addWidget(self.costLabel)
        self.costLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.costLineEdit.setEnabled(True)
        self.costLineEdit.setObjectName("costLineEdit")
        self.verticalLayout.addWidget(self.costLineEdit)
        self.expandedNodesLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.expandedNodesLabel.setObjectName("expandedNodesLabel")
        self.verticalLayout.addWidget(self.expandedNodesLabel)
        self.expandedNodesLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.expandedNodesLineEdit.setEnabled(True)
        self.expandedNodesLineEdit.setObjectName("expandedNodesLineEdit")
        self.verticalLayout.addWidget(self.expandedNodesLineEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(520, 10, 251, 214))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.algorithmComboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.algorithmComboBox.setObjectName("algorithmComboBox")
        self.algorithmComboBox.addItem("")
        self.algorithmComboBox.addItem("")
        self.algorithmComboBox.addItem("")
        self.algorithmComboBox.addItem("")
        self.verticalLayout_2.addWidget(self.algorithmComboBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.paramForm = QtWidgets.QFormLayout()
        self.paramForm.setObjectName("paramForm")
        self.paramLabel_1 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.paramLabel_1.setObjectName("paramLabel_1")
        self.paramForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.paramLabel_1)
        self.paramLineEdit_1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.paramLineEdit_1.setObjectName("paramLineEdit_1")
        self.paramForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.paramLineEdit_1)
        self.paramLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.paramLabel_2.setObjectName("paramLabel_2")
        self.paramForm.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.paramLabel_2)
        self.paramLineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.paramLineEdit_2.setObjectName("paramLineEdit_2")
        self.paramForm.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.paramLineEdit_2)
        self.paramSelectLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.paramSelectLabel.setObjectName("paramSelectLabel")
        self.paramForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.paramSelectLabel)
        self.paramComboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.paramComboBox.setObjectName("paramComboBox")
        self.paramComboBox.addItem("")
        self.paramComboBox.addItem("")
        self.paramForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.paramComboBox)
        self.verticalLayout_2.addLayout(self.paramForm)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.solveButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.solveButton.setObjectName("solveButton")
        self.horizontalLayout.addWidget(self.solveButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))
        self.runningTimeLabel.setText(_translate("MainWindow", "Running Time"))
        self.costLabel.setText(_translate("MainWindow", "Cost"))
        self.expandedNodesLabel.setText(_translate("MainWindow", "Expanded Nodes"))
        self.algorithmComboBox.setItemText(0, _translate("MainWindow", "Hill Climbing"))
        self.algorithmComboBox.setItemText(1, _translate("MainWindow", "Beam Search"))
        self.algorithmComboBox.setItemText(2, _translate("MainWindow", "Genetic Algorithm"))
        self.algorithmComboBox.setItemText(3, _translate("MainWindow", "CSP"))
        self.paramLabel_1.setText(_translate("MainWindow", "TextLabel"))
        self.paramLabel_2.setText(_translate("MainWindow", "TextLabel"))
        self.paramSelectLabel.setText(_translate("MainWindow", "Resolver"))
        self.paramComboBox.setItemText(0, _translate("MainWindow", "Random Restart"))
        self.paramComboBox.setItemText(1, _translate("MainWindow", "Sideway"))
        self.solveButton.setText(_translate("MainWindow", "Solve"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionLoad.setText(_translate("MainWindow", "Load From File"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
